version: '3.7'  

services: 
  backend: 
    image: myfirstbackend
    environment:
      - LC_ALL=C.UTF-8
      - FRONT_URL=http://localhost:5000
    ports: 
      - 8000:8000

  frontend:
    image: myfirstnode
    environment:
      - LC_ALL=C.UTF-8
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000 

